# Generated by Django 2.2 on 2019-04-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=30)),
                ('leagues_table', models.CharField(max_length=200)),
                ('url', models.SlugField(default='url', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(default='Team', max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('gd', models.IntegerField(default=0)),
                ('league_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
            options={
                'verbose_name': 'Standing',
                'ordering': ['-points', '-gd', 'position'],
            },
        ),
        migrations.CreateModel(
            name='south_america_competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('south_america_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
        ),
        migrations.CreateModel(
            name='others_competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('others_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
        ),
        migrations.CreateModel(
            name='north_america_competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('north_america_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
        ),
        migrations.CreateModel(
            name='europe_competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('europe_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
        ),
        migrations.CreateModel(
            name='australia_competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('australia_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
        ),
        migrations.CreateModel(
            name='asia_competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asia_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
        ),
        migrations.CreateModel(
            name='africa_competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('africa_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Table')),
            ],
        ),
    ]
