# Generated by Django 2.2 on 2019-04-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standings',
            options={'ordering': ['league_name'], 'verbose_name': 'Standing'},
        ),
    ]
