# Generated by Django 2.2 on 2019-04-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(blank=True, max_length=500, null=True)),
                ('embed_video_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
