# Generated by Django 2.2 on 2019-04-16 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scores_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 4, 16, 22, 26, 26, 368508, tzinfo=utc))),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.scores_date')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.Table')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='home_goal_scorers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('second_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('third_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fourth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fifth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('sixth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('seventh_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('eighth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('nineth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('tenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('eleventh_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('twelfth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('thirteenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fourteenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fifteenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('sixteenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('seventeenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('eighteenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('nineteenth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('twentieth_home_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.score')),
            ],
        ),
        migrations.CreateModel(
            name='away_goal_scorers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('second_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('third_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fourth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fifth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('sixth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('seventh_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('eighth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('nineth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('tenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('eleventh_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('twelfth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('thirteenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fourteenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('fifteenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('sixteenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('seventeenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('eighteenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('nineteenth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('twentieth_away_scorer', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.score')),
            ],
        ),
    ]
