# Generated by Django 2.2 on 2019-04-16 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_date',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 22, 29, 0, 967550, tzinfo=utc), unique=True),
        ),
    ]
