# Generated by Django 2.2 on 2019-04-17 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20190416_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='away_team_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='home_team_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='scores_date',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 17, 15, 50, 22, 831776, tzinfo=utc), unique=True),
        ),
    ]
