# Generated by Django 2.2.1 on 2020-02-03 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20190417_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_date',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 16, 55, 34, 321272, tzinfo=utc), unique=True),
        ),
    ]
