# Generated by Django 3.0.3 on 2020-04-19 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20200205_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_date',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 19, 7, 51, 11, 845516, tzinfo=utc), unique=True),
        ),
    ]
