# Generated by Django 3.0.3 on 2020-04-20 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20200419_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_date',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 20, 9, 25, 8, 125562, tzinfo=utc), unique=True),
        ),
    ]
