# Generated by Django 2.2 on 2019-04-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='football_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('images', models.URLField()),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('news', models.TextField()),
                ('url', models.SlugField(editable=False, max_length=500, null=True)),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scores.score')),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
    ]
