# Generated by Django 3.0.3 on 2020-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200205_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='football_posts',
            name='images',
        ),
        migrations.AddField(
            model_name='football_posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images'),
        ),
    ]
