# Generated by Django 2.2 on 2019-04-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_league', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Player_name', models.CharField(max_length=500)),
                ('From', models.CharField(max_length=200)),
                ('To', models.CharField(max_length=200)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.League_name')),
            ],
            options={
                'verbose_name': 'Transfer',
                'ordering': ['-date'],
            },
        ),
    ]
